package com.filo.app.ui

import androidx.compose.runtime.Composable
import com.filo.app.FiloApplication
import com.filo.app.LanguagePreference
import java.util.Locale

/** Shared source-key catalog for UI text that is not naturally backed by a resource id. */
object AppStrings {
    private val translations = mapOf(
        "en" to mapOf(
            "認証が設定されていません" to "Authentication is not configured", "APIの設定を確認してください。" to "Check the API configuration.", "Unable to connect" to "Unable to connect", "Check your internet connection and try again." to "Check your internet connection and try again.", "Retry" to "Retry", "メールアドレスと8文字以上のパスワードが必要です" to "An email address and a password of at least 8 characters are required", "メールアドレスを入力してください" to "Enter your email address", "パスワードリセットメールを送信しました" to "Password reset email sent", "リセットリンクを開いてください" to "Open the reset link", "新しいパスワードを入力してください" to "Enter a new password", "リセットリンクと8文字以上のパスワードを確認してください" to "Check the reset link and password (at least 8 characters)", "認証に失敗しました" to "Authentication failed", "認証トークンを取得できませんでした" to "Could not obtain an authentication token", "パスワードを変更できませんでした" to "Could not change the password", "パスワードを変更しました" to "Password changed",
            "サインイン" to "Sign in", "パスワードをお忘れですか？" to "Forgot your password?", "アカウントを作成" to "Create account", "アカウント作成" to "Create account", "サインインへ戻る" to "Back to sign in", "リセットメールを送信" to "Send reset email", "コードを確認" to "Verify code", "パスワードを変更" to "Change password", "メールアドレス" to "Email address", "パスワード" to "Password", "確認" to "Confirm", "記事" to "Articles",
            "記事を追加" to "Add article", "戻る" to "Back", "URLをリーディングリストに保存します。" to "Save the URL to your reading list.", "記事URL" to "Article URL", "保存中…" to "Saving…", "追加" to "Add", "フィードを追加" to "Add feed", "RSS/Atom URL または サイトURL" to "RSS/Atom URL or site URL", "タグ" to "Tag", "新規タグ（カンマ区切り）" to "New tags (comma-separated)", "フィードを確認中…" to "Checking feed…", "追加完了" to "Added", "記事の取得が完了しています。" to "Articles are ready.", "記事取得中" to "Fetching articles", "購読の追加は完了しました。記事を取得しています。" to "Subscription added. Fetching articles.", "初回取得失敗" to "Initial fetch failed", "再試行" to "Retry", "再試行中…" to "Retrying…", "記事一覧へ" to "View articles",
            "全ての記事" to "All articles", "リーディングリスト" to "Reading list", "ブックマーク" to "Bookmarks", "未読" to "Unread", "既読" to "Read", "未読にする" to "Mark unread", "既読にする" to "Mark read", "翻訳" to "Translation", "原文" to "Original", "表示できる記事がありません。" to "No articles to display.", "まだ購読がありません。" to "You have no subscriptions yet.", "記事一覧を読み込んでいます…" to "Loading articles…", "記事を取得しています…" to "Fetching articles…", "リーディングリストに保存した記事はありません。" to "There are no saved articles in the reading list.", "更新" to "Refresh", "更新中…" to "Refreshing…", "すべて既読にする" to "Mark all as read", "既読記事を削除" to "Remove read articles", "既読の記事をリーディングリストから削除しますか？" to "Remove read articles from the reading list?",
            "購読管理" to "Subscriptions", "タグ管理" to "Tags", "処理ステータス" to "Status", "設定" to "Settings", "表示設定" to "Display settings", "フィードメニュー" to "Feed menu", "メニュー" to "Menu", "閉じる" to "Close", "展開" to "Expand", "折りたたむ" to "Collapse", "タグなし" to "No tag", "タグを編集" to "Edit tags", "タグを上へ" to "Move tag up", "タグを下へ" to "Move tag down", "上へ" to "Move up", "下へ" to "Move down", "名前変更" to "Rename", "名前を変更" to "Rename", "タグ名を変更" to "Rename tag", "購読解除" to "Unsubscribe", "購読の操作" to "Subscription actions", "サイトを開く" to "Open site", "フィードURLを表示" to "Show feed URL", "フィードURL" to "Feed URL", "このフィードを更新" to "Refresh this feed", "購読が見つかりません" to "Subscription not found", "購読がありません。" to "No subscriptions.", "この購読は削除されたか、表示できません。" to "This subscription was deleted or cannot be displayed.",
            "状態" to "Status", "すべて" to "All", "問題あり" to "Needs attention", "取得中" to "Fetching", "取得中…" to "Fetching…", "停止" to "Paused", "取得" to "Fetch", "最終取得" to "Last fetched", "検索" to "Search", "購読名で検索" to "Search subscriptions", "条件に一致する購読がありません。" to "No subscriptions match the filters.", "操作" to "Actions", "並び順" to "Sort order", "公開日時が新しい順" to "Newest published first", "取得日時が新しい順" to "Newest fetched first", "既読状態" to "Read status", "既読の扱い" to "Read handling", "既読で並び替えない" to "Do not sort by read status", "既読は下" to "Read last", "既読は上" to "Read first", "購読一覧を絞り込み" to "Filter subscriptions",
            "約%d秒ごとに自動更新" to "Auto-refreshes about every %d seconds", "購読一覧（%d件）" to "Subscriptions (%d)", "購読 %d件・記事 %d件" to "%d subscriptions · %d articles", "最終公開 %s" to "Last published %s", "%d件" to "%d", "%d件の購読" to "%d subscriptions", "追加 %d / スキップ %d / 失敗 %d" to "Added %d / Skipped %d / Failed %d", "フィードの取得を開始しました。" to "Feed fetch started.", "取得対象のフィードがありません。" to "There are no feeds to fetch.", "最近取得済みのため、今回の取得対象はありませんでした。" to "Everything was fetched recently; nothing was queued.", "取得に時間がかかっています。あとで再度更新してください。" to "Fetching is taking longer than expected. Try again later.",
            "読み上げ設定" to "Reading settings", "現在のページ" to "Current page", "読み上げるページを開いてください" to "Open a page to read aloud", "読み上げを停止" to "Stop reading aloud", "このページを読み上げ" to "Read this page aloud", "読み上げできるページなし" to "No readable page", "リストに追加" to "Add to list", "内容" to "Content", "本文を抽出" to "Extract article", "表示中の文章" to "Visible text", "速度" to "Speed", "声" to "Voice", "自動" to "Automatic", "読み上げ中" to "Reading aloud", "ショートカット" to "Shortcuts", "J / ↓  次の記事" to "J / ↓  Next article", "K / ↑  前の記事" to "K / ↑  Previous article", "Space  読み上げ開始／停止" to "Space  Start / stop reading aloud", "S  リーディングリストに追加" to "S  Add to reading list", "V  元記事を開く" to "V  Open original", "共有ページ" to "Shared page", "未読の記事がありません。" to "There are no unread articles.", "本文を抽出できませんでした。" to "The article text could not be extracted.", "リーディングリストを開始できませんでした。" to "Could not start the reading list.", "リーディングリストに追加できませんでした。" to "Could not add to the reading list.", "リーディングリストから削除できませんでした。" to "Could not remove from the reading list.", "リーディングリストに記事がありません。" to "There are no articles in the reading list.",
            "言語" to "Language", "日本語" to "Japanese", "English" to "English", "简体中文" to "Simplified Chinese", "한국어" to "Korean", "Español" to "Spanish", "テーマ" to "Theme", "システム" to "System", "ライト" to "Light", "ダーク" to "Dark", "原文のまま読む言語" to "Languages to read in original", "翻訳の準備" to "Prepare translation", "言語を確認" to "Check languages", "リンクを常にブラウザで開く" to "Always open links in browser", "インポート" to "Import", "エクスポート" to "Export", "インポート処理中…" to "Importing…", "インポート完了" to "Import complete", "インポート失敗" to "Import failed", "追加 %d / スキップ %d / 失敗 %d" to "Added %d / Skipped %d / Failed %d", "既読履歴について" to "Read history", "セッション" to "Session", "サインアウト" to "Sign out", "危険な操作" to "Dangerous actions", "アカウント削除" to "Delete account", "アカウントを削除しますか？" to "Delete your account?", "この操作は取り消せません。" to "This cannot be undone.", "削除する" to "Delete", "キャンセル" to "Cancel",
            "ネットワークに接続できません。時間をおいて再試行してください。" to "Unable to connect. Please try again later.", "サインインが必要です。" to "Please sign in.", "入力内容を確認してください。" to "Please check your input.", "対象が見つかりません。" to "Not found.", "操作が競合しました。最新の状態を確認してください。" to "The operation conflicted. Check the latest state.", "操作が混み合っています。少し待ってから再試行してください。" to "Things are busy. Please wait and try again.", "このフィードはすでに購読しています。" to "You already subscribe to this feed.", "同じ名前のタグがすでにあります。" to "A tag with this name already exists.", "タグが見つかりません。" to "Tag not found.", "記事が見つかりません。" to "Article not found.", "ページ情報が無効です。再読み込みしてください。" to "The page information is invalid. Reload and try again.", "このURLからフィードを見つけられませんでした。" to "Could not find a feed at this URL.", "URLに接続できませんでした。アドレスを確認してください。" to "Could not connect to the URL. Check the address.", "初回の記事取得に失敗しました。" to "The initial article fetch failed.", "認証トークンを取得できませんでした。" to "Could not obtain an authentication token.", "アカウント削除処理に失敗しました。再試行してください。" to "Account deletion failed. Please try again.",
        ),
        "zh" to mapOf("認証が設定されていません" to "未配置身份验证", "APIの設定を確認してください。" to "请检查 API 设置。", "サインイン" to "登录", "アカウント作成" to "创建账户", "アカウントを作成" to "创建账户", "サインインへ戻る" to "返回登录", "メールアドレス" to "邮箱地址", "パスワード" to "密码", "記事を追加" to "添加文章", "戻る" to "返回", "追加" to "添加", "保存中…" to "保存中…", "全ての記事" to "全部文章", "リーディングリスト" to "阅读列表", "ブックマーク" to "书签", "未読" to "未读", "既読" to "已读", "更新" to "刷新", "すべて既読にする" to "全部标记为已读", "購読管理" to "订阅管理", "タグ管理" to "标签", "設定" to "设置", "言語" to "语言", "テーマ" to "主题", "システム" to "跟随系统", "ライト" to "浅色", "ダーク" to "深色", "メニュー" to "菜单", "閉じる" to "关闭", "フィードを追加" to "添加订阅源", "タグ" to "标签", "記事URL" to "文章 URL", "読み上げ設定" to "朗读设置", "現在のページ" to "当前页面", "読み上げるページを開いてください" to "打开要朗读的页面", "読み上げを停止" to "停止朗读", "このページを読み上げ" to "朗读此页面", "リストに追加" to "加入列表", "速度" to "速度", "声" to "声音", "自動" to "自动", "ショートカット" to "快捷键", "共有ページ" to "共享页面", "停止" to "停止", "削除する" to "删除", "キャンセル" to "取消", "再試行" to "重试", "購読がありません。" to "没有订阅。", "購読が見つかりません" to "找不到订阅", "記事取得中" to "正在获取文章", "取得中…" to "获取中…", "取得" to "获取", "状態" to "状态", "すべて" to "全部", "問題あり" to "需要注意", "検索" to "搜索", "購読名で検索" to "搜索订阅", "購読解除" to "取消订阅", "サイトを開く" to "打开网站", "名前変更" to "重命名", "タグなし" to "无标签", "タグを編集" to "编辑标签", "上へ" to "上移", "下へ" to "下移", "オフ" to "关闭", "オン" to "开启", "翻訳" to "翻译", "原文" to "原文", "取得対象のフィードがありません。" to "没有可获取的订阅源。", "フィードの取得を開始しました。" to "已开始获取订阅源。", "取得に時間がかかっています。あとで再度更新してください。" to "获取时间较长，请稍后重试。", "読み込み中…" to "加载中…", "記事一覧を読み込んでいます…" to "正在加载文章…", "リーディングリストに記事がありません。" to "阅读列表中没有文章。", "未読の記事がありません。" to "没有未读文章。", "本文を抽出できませんでした。" to "无法提取文章正文。", "認証に失敗しました" to "认证失败", "ネットワークに接続できません。時間をおいて再試行してください。" to "无法连接网络，请稍后重试。", "サインインが必要です。" to "请先登录。", "English" to "英语", "简体中文" to "简体中文", "한국어" to "韩语", "Español" to "西班牙语"),
        "ko" to mapOf("認証が設定されていません" to "인증이 설정되지 않았습니다", "APIの設定を確認してください。" to "API 설정을 확인하세요.", "サインイン" to "로그인", "アカウント作成" to "계정 만들기", "アカウントを作成" to "계정 만들기", "サインインへ戻る" to "로그인으로 돌아가기", "メールアドレス" to "이메일 주소", "パスワード" to "비밀번호", "記事を追加" to "기사 추가", "戻る" to "뒤로", "追加" to "추가", "保存中…" to "저장 중…", "全ての記事" to "모든 기사", "リーディングリスト" to "읽기 목록", "ブックマーク" to "북마크", "未読" to "읽지 않음", "既読" to "읽음", "更新" to "새로고침", "すべて既読にする" to "모두 읽음으로 표시", "購読管理" to "구독 관리", "タグ管理" to "태그", "設定" to "설정", "言語" to "언어", "テーマ" to "테마", "システム" to "시스템 설정", "ライト" to "라이트", "ダーク" to "다크", "メニュー" to "메뉴", "閉じる" to "닫기", "フィードを追加" to "피드 추가", "タグ" to "태그", "記事URL" to "기사 URL", "読み上げ設定" to "읽어주기 설정", "現在のページ" to "현재 페이지", "読み上げるページを開いてください" to "읽어줄 페이지를 여세요", "読み上げを停止" to "읽어주기 중지", "このページを読み上げ" to "이 페이지 읽어주기", "リストに追加" to "목록에 추가", "速度" to "속도", "声" to "음성", "自動" to "자동", "ショートカット" to "단축키", "共有ページ" to "공유 페이지", "停止" to "중지", "削除する" to "삭제", "キャンセル" to "취소", "再試行" to "다시 시도", "購読がありません。" to "구독이 없습니다.", "購読が見つかりません" to "구독을 찾을 수 없습니다", "記事取得中" to "기사 가져오는 중", "取得中…" to "가져오는 중…", "取得" to "가져오기", "状態" to "상태", "すべて" to "전체", "問題あり" to "주의 필요", "検索" to "검색", "購読名で検索" to "구독 이름 검색", "購読解除" to "구독 취소", "サイトを開く" to "사이트 열기", "名前変更" to "이름 변경", "タグなし" to "태그 없음", "タグを編集" to "태그 편집", "上へ" to "위로", "下へ" to "아래로", "オフ" to "끔", "オン" to "켬", "翻訳" to "번역", "原文" to "원문", "取得対象のフィードがありません。" to "가져올 피드가 없습니다.", "フィードの取得を開始しました。" to "피드 가져오기를 시작했습니다.", "読み込み中…" to "로드 중…", "記事一覧を読み込んでいます…" to "기사 목록을 불러오는 중…", "リーディングリストに記事がありません。" to "읽기 목록에 기사가 없습니다.", "未読の記事がありません。" to "읽지 않은 기사가 없습니다.", "本文を抽出できませんでした。" to "본문을 추출할 수 없습니다.", "認証に失敗しました" to "인증에 실패했습니다", "ネットワークに接続できません。時間をおいて再試行してください。" to "네트워크에 연결할 수 없습니다. 나중에 다시 시도하세요.", "サインインが必要です。" to "로그인해야 합니다.", "English" to "영어", "简体中文" to "중국어(간체)", "한국어" to "한국어", "Español" to "스페인어"),
        "es" to mapOf("認証が設定されていません" to "La autenticación no está configurada", "APIの設定を確認してください。" to "Comprueba la configuración de la API.", "サインイン" to "Iniciar sesión", "アカウント作成" to "Crear cuenta", "アカウントを作成" to "Crear cuenta", "サインインへ戻る" to "Volver a iniciar sesión", "メールアドレス" to "Correo electrónico", "パスワード" to "Contraseña", "記事を追加" to "Añadir artículo", "戻る" to "Atrás", "追加" to "Añadir", "保存中…" to "Guardando…", "全ての記事" to "Todos los artículos", "リーディングリスト" to "Lista de lectura", "ブックマーク" to "Marcadores", "未読" to "No leídos", "既読" to "Leídos", "更新" to "Actualizar", "すべて既読にする" to "Marcar todo como leído", "購読管理" to "Suscripciones", "タグ管理" to "Etiquetas", "設定" to "Ajustes", "言語" to "Idioma", "テーマ" to "Tema", "システム" to "Sistema", "ライト" to "Claro", "ダーク" to "Oscuro", "メニュー" to "Menú", "閉じる" to "Cerrar", "フィードを追加" to "Añadir feed", "タグ" to "Etiqueta", "記事URL" to "URL del artículo", "読み上げ設定" to "Configuración de lectura", "現在のページ" to "Página actual", "読み上げるページを開いてください" to "Abre una página para leerla en voz alta", "読み上げを停止" to "Detener lectura", "このページを読み上げ" to "Leer esta página en voz alta", "リストに追加" to "Añadir a la lista", "速度" to "Velocidad", "声" to "Voz", "自動" to "Automático", "ショートカット" to "Atajos", "共有ページ" to "Página compartida", "停止" to "Detener", "削除する" to "Eliminar", "キャンセル" to "Cancelar", "再試行" to "Reintentar", "購読がありません。" to "No hay suscripciones.", "購読が見つかりません" to "Suscripción no encontrada", "記事取得中" to "Obteniendo artículos", "取得中…" to "Obteniendo…", "取得" to "Obtener", "状態" to "Estado", "すべて" to "Todo", "問題あり" to "Requiere atención", "検索" to "Buscar", "購読名で検索" to "Buscar suscripciones", "購読解除" to "Cancelar suscripción", "サイトを開く" to "Abrir sitio", "名前変更" to "Cambiar nombre", "タグなし" to "Sin etiqueta", "タグを編集" to "Editar etiquetas", "上へ" to "Subir", "下へ" to "Bajar", "オフ" to "Desactivado", "オン" to "Activado", "翻訳" to "Traducción", "原文" to "Original", "取得対象のフィードがありません。" to "No hay feeds para obtener.", "フィードの取得を開始しました。" to "Se inició la obtención del feed.", "読み込み中…" to "Cargando…", "記事一覧を読み込んでいます…" to "Cargando artículos…", "リーディングリストに記事がありません。" to "No hay artículos en la lista de lectura.", "未読の記事がありません。" to "No hay artículos sin leer.", "本文を抽出できませんでした。" to "No se pudo extraer el texto del artículo.", "認証に失敗しました" to "Error de autenticación", "ネットワークに接続できません。時間をおいて再試行してください。" to "No se puede conectar a la red. Inténtalo más tarde.", "サインインが必要です。" to "Debes iniciar sesión.", "English" to "Inglés", "简体中文" to "Chino simplificado", "한국어" to "Coreano", "Español" to "Español"),
    )

    // The original Android resources cover the settings screen. These
    // supplemental entries keep the newer Compose surfaces in the selected
    // language as well; commonEnglish remains the safe fallback for an
    // untranslated server error or future UI key.
    private val supplementalTranslations = mapOf(
        "zh" to mapOf(
            "%d件" to "%d 项", "%d件の購読" to "%d 个订阅", "%d件のフィードの取得を開始しました。" to "已开始获取 %d 个订阅源。", "約%d秒ごとに自動更新" to "约每 %d 秒自动刷新", "購読一覧（%d件）" to "订阅列表（%d）", "購読 %d件・記事 %d件" to "%d 个订阅 · %d 篇文章", "最終公開 %s" to "最后发布 %s", "最終取得 %s" to "最后获取 %s", "並び替え: %s" to "排序：%s", "購読は作成されましたが、%s" to "订阅已创建，但%s", "再読み込み" to "重新加载", "操作" to "操作", "購読" to "订阅", "すべて取得" to "全部获取", "取得" to "获取", "フィード追加" to "添加订阅源", "更新停止中" to "已暂停更新", "しばらく更新なし" to "近期没有更新", "購読詳細" to "订阅详情", "購読一覧へ戻る" to "返回订阅列表", "購読名を変更" to "重命名订阅", "空欄でフィード名に戻す" to "留空以使用订阅源名称", "変更" to "修改", "コピー" to "复制", "このフィードを更新" to "刷新此订阅源", "この購読は削除されたか、表示できません。" to "此订阅已删除或无法显示。", "購読がありません。" to "没有订阅。", "購読記事を読み込んでいます…" to "正在加载订阅文章…", "次の記事を読み込んでいます…" to "正在加载下一篇文章…", "この購読を解除しますか？" to "确定取消此订阅吗？", "ブックマークした記事は残ります。" to "已收藏的文章会保留。", "タグ名を変更" to "重命名标签", "新しいタグ名" to "新标签名称", "タグ名" to "标签名称", "タグがありません。上の入力欄から作成できます。" to "还没有标签。请使用上方输入框创建。", "色 (#hex)" to "颜色（#hex）", "解除" to "清除", "保存" to "保存", "編集" to "编辑", "購読は削除されません。" to "订阅不会被删除。", "タグ「%s」を削除しますか？" to "确定删除标签“%s”吗？", "既読の記事をリーディングリストから削除しますか？" to "要从阅读列表中删除已读文章吗？", "既読記事を削除" to "删除已读文章", "ショートカット" to "快捷键", "リセットコード" to "重置代码", "パスワードをリセット" to "重置密码", "コードを確認" to "确认代码", "パスワードを変更" to "修改密码", "パスワードを変更しました" to "密码已修改", "パスワードを変更できませんでした" to "无法修改密码", "パスワードをお忘れですか？" to "忘记密码？", "メールアドレスを入力してください" to "请输入邮箱地址", "初回の記事取得に失敗しました。" to "首次获取文章失败。", "フィードに接続できませんでした。" to "无法连接订阅源。", "フィードを見つけられませんでした。" to "找不到订阅源。", "アカウント削除" to "删除账户", "インポート完了" to "导入完成", "インポート失敗" to "导入失败", "状態を確認しています…" to "正在检查状态…", "削除完了" to "已删除", "アカウントの削除が完了しました。ご利用ありがとうございました。" to "账户已删除。感谢您使用 Filo。", "再ログインしてもデータは復元されません。" to "重新登录也无法恢复数据。", "削除処理に失敗しました" to "删除失败", "削除処理中…" to "正在删除…", "設定へ戻る" to "返回设置", "進行中の削除処理はありません。" to "没有正在进行的删除操作。", "確認しています…" to "正在检查…", "準備済み" to "已准备", "ダウンロード" to "下载", "ダウンロード中…" to "正在下载…", "この端末では非対応" to "此设备不支持", "購読しているフィードに、翻訳が必要な言語はありません。" to "订阅的订阅源中没有需要翻译的语言。", "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "未列出的语言会以原文显示。", "タイトルを翻訳" to "翻译标题", "タイトルを翻訳（オン）" to "翻译标题（开）", "タイトルを翻訳（オフ）" to "翻译标题（关）", "再生" to "播放", "一時停止" to "暂停", "一時停止中" to "已暂停", "再生中 %d/%d" to "播放中 %d/%d", "読み上げ" to "朗读", "リスト" to "列表",
        ),
        "ko" to mapOf(
            "%d件" to "%d개", "%d件の購読" to "%d개 구독", "%d件のフィードの取得を開始しました。" to "%d개 피드 가져오기를 시작했습니다.", "約%d秒ごとに自動更新" to "약 %d초마다 자동 새로고침", "購読一覧（%d件）" to "구독 목록(%d개)", "購読 %d件・記事 %d件" to "구독 %d개 · 기사 %d개", "最終公開 %s" to "최근 공개 %s", "最終取得 %s" to "최근 가져옴 %s", "並び替え: %s" to "정렬: %s", "購読は作成されましたが、%s" to "구독은 생성되었지만 %s", "再読み込み" to "다시 로드", "操作" to "작업", "購読" to "구독", "すべて取得" to "모두 가져오기", "取得" to "가져오기", "フィード追加" to "피드 추가", "更新停止中" to "업데이트 중지됨", "しばらく更新なし" to "최근 업데이트 없음", "購読詳細" to "구독 상세", "購読一覧へ戻る" to "구독 목록으로 돌아가기", "購読名を変更" to "구독 이름 변경", "空欄でフィード名に戻す" to "비워 두면 피드 이름 사용", "変更" to "변경", "コピー" to "복사", "このフィードを更新" to "이 피드 새로고침", "この購読は削除されたか、表示できません。" to "이 구독은 삭제되었거나 표시할 수 없습니다.", "購読がありません。" to "구독이 없습니다.", "購読記事を読み込んでいます…" to "구독 기사를 불러오는 중…", "次の記事を読み込んでいます…" to "다음 기사를 불러오는 중…", "この購読を解除しますか？" to "이 구독을 취소할까요?", "ブックマークした記事は残ります。" to "북마크한 기사는 유지됩니다.", "タグ名を変更" to "태그 이름 변경", "新しいタグ名" to "새 태그 이름", "タグ名" to "태그 이름", "タグがありません。上の入力欄から作成できます。" to "태그가 없습니다. 위 입력란에서 만들어 보세요.", "色 (#hex)" to "색상(#hex)", "解除" to "지우기", "保存" to "저장", "編集" to "편집", "購読は削除されません。" to "구독은 삭제되지 않습니다.", "タグ「%s」を削除しますか？" to "태그 '%s'를 삭제할까요?", "既読の記事をリーディングリストから削除しますか？" to "읽은 기사를 읽기 목록에서 삭제할까요?", "既読記事を削除" to "읽은 기사 삭제", "ショートカット" to "단축키", "リセットコード" to "재설정 코드", "パスワードをリセット" to "비밀번호 재설정", "コードを確認" to "코드 확인", "パスワードを変更" to "비밀번호 변경", "パスワードを変更しました" to "비밀번호를 변경했습니다", "パスワードを変更できませんでした" to "비밀번호를 변경할 수 없습니다", "パスワードをお忘れですか？" to "비밀번호를 잊으셨나요?", "メールアドレスを入力してください" to "이메일 주소를 입력하세요", "初回の記事取得に失敗しました。" to "첫 기사 가져오기에 실패했습니다.", "フィードに接続できませんでした。" to "피드에 연결할 수 없습니다.", "フィードを見つけられませんでした。" to "피드를 찾을 수 없습니다.", "アカウント削除" to "계정 삭제", "インポート完了" to "가져오기 완료", "インポート失敗" to "가져오기 실패", "状態を確認しています…" to "상태 확인 중…", "削除完了" to "삭제됨", "アカウントの削除が完了しました。ご利用ありがとうございました。" to "계정이 삭제되었습니다. Filo를 이용해 주셔서 감사합니다.", "再ログインしてもデータは復元されません。" to "다시 로그인해도 데이터는 복구되지 않습니다.", "削除処理に失敗しました" to "삭제에 실패했습니다", "削除処理中…" to "삭제 중…", "設定へ戻る" to "설정으로 돌아가기", "進行中の削除処理はありません。" to "진행 중인 삭제 작업이 없습니다.", "確認しています…" to "확인 중…", "準備済み" to "준비됨", "ダウンロード" to "다운로드", "ダウンロード中…" to "다운로드 중…", "この端末では非対応" to "이 기기에서 지원되지 않음", "購読しているフィードに、翻訳が必要な言語はありません。" to "구독 중인 피드에 번역이 필요한 언어가 없습니다.", "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "목록에 없는 언어의 기사는 원문으로 표시합니다.", "タイトルを翻訳" to "제목 번역", "タイトルを翻訳（オン）" to "제목 번역(켜짐)", "タイトルを翻訳（オフ）" to "제목 번역(꺼짐)", "再生" to "재생", "一時停止" to "일시 정지", "一時停止中" to "일시 정지됨", "再生中 %d/%d" to "재생 중 %d/%d", "読み上げ" to "낭독", "リスト" to "목록",
        ),
        "es" to mapOf(
            "%d件" to "%d", "%d件の購読" to "%d suscripciones", "%d件のフィードの取得を開始しました。" to "Se inició la obtención de %d feeds.", "約%d秒ごとに自動更新" to "Se actualiza cada aproximadamente %d segundos", "購読一覧（%d件）" to "Suscripciones (%d)", "購読 %d件・記事 %d件" to "%d suscripciones · %d artículos", "最終公開 %s" to "Última publicación %s", "最終取得 %s" to "Última obtención %s", "並び替え: %s" to "Ordenar: %s", "購読は作成されましたが、%s" to "La suscripción se creó, pero %s", "再読み込み" to "Recargar", "操作" to "Acciones", "購読" to "Suscripción", "すべて取得" to "Obtener todo", "取得" to "Obtener", "フィード追加" to "Añadir feed", "更新停止中" to "Actualizaciones pausadas", "しばらく更新なし" to "Sin actualizaciones recientes", "購読詳細" to "Detalles de la suscripción", "購読一覧へ戻る" to "Volver a suscripciones", "購読名を変更" to "Cambiar nombre de suscripción", "空欄でフィード名に戻す" to "Déjalo vacío para usar el nombre del feed", "変更" to "Cambiar", "コピー" to "Copiar", "このフィードを更新" to "Actualizar este feed", "この購読は削除されたか、表示できません。" to "Esta suscripción se eliminó o no se puede mostrar.", "購読がありません。" to "No hay suscripciones.", "購読記事を読み込んでいます…" to "Cargando artículos de la suscripción…", "次の記事を読み込んでいます…" to "Cargando el siguiente artículo…", "この購読を解除しますか？" to "¿Cancelar esta suscripción?", "ブックマークした記事は残ります。" to "Los artículos guardados se conservarán.", "タグ名を変更" to "Cambiar nombre de etiqueta", "新しいタグ名" to "Nombre de la nueva etiqueta", "タグ名" to "Nombre de etiqueta", "タグがありません。上の入力欄から作成できます。" to "No hay etiquetas. Crea una con el campo superior.", "色 (#hex)" to "Color (#hex)", "解除" to "Borrar", "保存" to "Guardar", "編集" to "Editar", "購読は削除されません。" to "Las suscripciones no se eliminarán.", "タグ「%s」を削除しますか？" to "¿Eliminar la etiqueta «%s»?", "既読の記事をリーディングリストから削除しますか？" to "¿Eliminar los artículos leídos de la lista?", "既読記事を削除" to "Eliminar artículos leídos", "ショートカット" to "Atajos", "リセットコード" to "Código de restablecimiento", "パスワードをリセット" to "Restablecer contraseña", "コードを確認" to "Verificar código", "パスワードを変更" to "Cambiar contraseña", "パスワードを変更しました" to "Contraseña cambiada", "パスワードを変更できませんでした" to "No se pudo cambiar la contraseña", "パスワードをお忘れですか？" to "¿Olvidaste tu contraseña?", "メールアドレスを入力してください" to "Introduce tu correo electrónico", "初回の記事取得に失敗しました。" to "No se pudo obtener el primer artículo.", "フィードに接続できませんでした。" to "No se pudo conectar con el feed.", "フィードを見つけられませんでした。" to "No se encontró el feed.", "アカウント削除" to "Eliminar cuenta", "インポート完了" to "Importación completada", "インポート失敗" to "Error de importación", "状態を確認しています…" to "Comprobando el estado…", "削除完了" to "Eliminada", "アカウントの削除が完了しました。ご利用ありがとうございました。" to "Tu cuenta se ha eliminado. Gracias por usar Filo.", "再ログインしてもデータは復元されません。" to "Volver a iniciar sesión no restaurará los datos.", "削除処理に失敗しました" to "Error de eliminación", "削除処理中…" to "Eliminando…", "設定へ戻る" to "Volver a ajustes", "進行中の削除処理はありません。" to "No hay ninguna eliminación en curso.", "確認しています…" to "Comprobando…", "準備済み" to "Listo", "ダウンロード" to "Descargar", "ダウンロード中…" to "Descargando…", "この端末では非対応" to "No compatible con este dispositivo", "購読しているフィードに、翻訳が必要な言語はありません。" to "Ninguno de tus feeds necesita traducción.", "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "Los artículos en idiomas no listados se muestran en su idioma original.", "タイトルを翻訳" to "Traducir títulos", "タイトルを翻訳（オン）" to "Traducir títulos (activado)", "タイトルを翻訳（オフ）" to "Traducir títulos (desactivado)", "再生" to "Reproducir", "一時停止" to "Pausar", "一時停止中" to "En pausa", "再生中 %d/%d" to "Reproduciendo %d/%d", "読み上げ" to "Lectura en voz alta", "リスト" to "Lista",
        ),
    )

    // Reuse the complete iOS catalog for Compose-only strings until each
    // platform resource catalog is split into Android string resources.
    private val resourceTranslations = mapOf(
        "en" to mapOf(
            "%d件のフィードの取得を開始しました。" to "%d feeds queued for fetching.",
            "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "Articles in languages not listed here stay in their original language.",
            "この画面を閉じても削除処理は継続されます。再ログインでデータが復活することはありません。" to "Deletion continues if you close this screen. Signing in again will not restore your data.",
            "この端末では非対応" to "Not supported on this device",
            "しばらく更新なし" to "No recent updates",
            "すべて取得" to "Fetch all",
            "アカウントの削除が完了しました。ご利用ありがとうございました。" to "Your account has been deleted. Thank you for using Filo.",
            "アカウントを削除すると購読・タグ・記事の状態がすべて削除され、再ログインしても復元されません。" to "Deleting your account removes subscriptions, tags, and article state. Signing in again will not restore them.",
            "コピー" to "Copy",
            "タグがありません。上の入力欄から作成できます。" to "No tags. Create one using the field above.",
            "タグ名" to "Tag name",
            "ダウンロード" to "Download",
            "フィード" to "Feeds",
            "フィードに接続できませんでした。" to "Could not connect to the feed.",
            "フィードを見つけられませんでした。" to "Could not find the feed.",
            "フィード追加" to "Add feed",
            "リスト" to "List",
            "一時停止" to "Pause",
            "並び替え: %s" to "Sort: %s",
            "保存" to "Save",
            "再ログインしてもデータは復元されません。" to "Your data cannot be restored by signing in again.",
            "分" to "m",
            "削除" to "Delete",
            "削除処理に失敗しました" to "Deletion failed",
            "削除処理は自動的に再試行されます。時間をおいてもこの状態が続く場合はお問い合わせください。" to "Deletion will be retried automatically. Contact support if this continues.",
            "削除処理中…" to "Deleting…",
            "削除完了" to "Deleted",
            "変更" to "Change",
            "新しいタグ名" to "New tag name",
            "新しいパスワード" to "New password",
            "日" to "d",
            "時間" to "h",
            "更新停止中" to "Updates paused",
            "次の記事を読み込んでいます…" to "Loading the next article…",
            "準備済み" to "Ready",
            "状態を確認しています…" to "Checking status…",
            "確認しています…" to "Checking…",
            "空欄でフィード名に戻す" to "Leave blank to use the feed name",
            "編集" to "Edit",
            "設定へ戻る" to "Back to settings",
            "読み上げ" to "Read aloud",
            "購読" to "Subscriptions",
            "購読しているフィードに、翻訳が必要な言語はありません。" to "None of your subscriptions need translation.",
            "購読は作成されましたが、%s" to "The subscription was created, but %s",
            "購読一覧へ戻る" to "Back to subscriptions",
            "購読名を変更" to "Rename subscription",
            "購読記事を読み込んでいます…" to "Loading subscription articles…",
            "購読詳細" to "Subscription details",
            "進行中の削除処理はありません。" to "There is no deletion in progress.",
            "閲覧履歴は既読記事として扱われます。記事一覧の絞り込みから既読記事を確認できます。" to "Reading history is treated as read articles. Use the article filters to view read articles.",
        ),
        "zh" to mapOf(
            "J / ↓  次の記事" to "J / ↓  下一篇文章",
            "K / ↑  前の記事" to "K / ↑  上一篇文章",
            "RSS/Atom URL または サイトURL" to "RSS/Atom URL 或网站 URL",
            "URLをリーディングリストに保存します。" to "将 URL 保存到阅读列表。",
            "V  元記事を開く" to "V  打开原文",
            "この画面を閉じても削除処理は継続されます。再ログインでデータが復活することはありません。" to "关闭此页面后删除仍会继续。重新登录也无法恢复数据。",
            "まだ購読がありません。" to "还没有订阅。",
            "アカウントを削除すると購読・タグ・記事の状態がすべて削除され、再ログインしても復元されません。" to "删除账户会删除订阅、标签和文章状态，重新登录也无法恢复。",
            "タグを上へ" to "上移标签",
            "タグを下へ" to "下移标签",
            "パスワードリセットメールを送信しました" to "密码重置邮件已发送",
            "フィード" to "订阅源",
            "フィードURL" to "订阅源 URL",
            "フィードURLを表示" to "显示订阅源 URL",
            "フィードを確認中…" to "正在检查订阅源…",
            "フィードメニュー" to "订阅源菜单",
            "リーディングリストに保存した記事はありません。" to "阅读列表中没有保存的文章。",
            "並び順" to "排序方式",
            "公開日時が新しい順" to "按发布时间从新到旧",
            "再試行中…" to "重试中…",
            "処理ステータス" to "处理状态",
            "分" to "分钟",
            "初回取得失敗" to "首次获取失败",
            "削除" to "删除",
            "削除処理は自動的に再試行されます。時間をおいてもこの状態が続く場合はお問い合わせください。" to "删除操作会自动重试。如果长时间没有变化，请联系支持。",
            "取得中" to "获取中",
            "取得日時が新しい順" to "按获取时间从新到旧",
            "名前を変更" to "重命名",
            "新しいパスワード" to "新密码",
            "新しいパスワードを入力してください" to "请输入新密码",
            "新規タグ（カンマ区切り）" to "新标签（用逗号分隔）",
            "既読で並び替えない" to "不按已读状态排序",
            "既読の扱い" to "已读处理",
            "既読は上" to "已读优先",
            "既読は下" to "已读置后",
            "既読状態" to "阅读状态",
            "日" to "天",
            "日本語" to "日语",
            "時間" to "小时",
            "最終取得" to "最后获取",
            "最近取得済みのため、今回の取得対象はありませんでした。" to "最近已获取过，本次没有新的获取任务。",
            "条件に一致する購読がありません。" to "没有符合条件的订阅。",
            "翻訳の準備" to "准备翻译",
            "表示できる記事がありません。" to "没有可显示的文章。",
            "表示設定" to "显示设置",
            "言語を確認" to "检查语言",
            "記事の取得が完了しています。" to "文章已准备就绪。",
            "記事を取得しています…" to "正在获取文章…",
            "記事一覧へ" to "查看文章",
            "読み上げ中" to "正在朗读",
            "購読の操作" to "订阅操作",
            "購読の追加は完了しました。記事を取得しています。" to "订阅已添加，正在获取文章。",
            "追加 %d / スキップ %d / 失敗 %d" to "添加 %d / 跳过 %d / 失败 %d",
            "追加完了" to "已添加",
            "閲覧履歴は既読記事として扱われます。記事一覧の絞り込みから既読記事を確認できます。" to "阅读历史会作为已读文章处理。可在文章列表筛选已读文章。",
        ),
        "ko" to mapOf(
            "J / ↓  次の記事" to "J / ↓  다음 기사",
            "K / ↑  前の記事" to "K / ↑  이전 기사",
            "RSS/Atom URL または サイトURL" to "RSS/Atom URL 또는 사이트 URL",
            "URLをリーディングリストに保存します。" to "URL을 읽기 목록에 저장합니다.",
            "V  元記事を開く" to "V  원문 열기",
            "この画面を閉じても削除処理は継続されます。再ログインでデータが復活することはありません。" to "이 화면을 닫아도 삭제는 계속됩니다. 다시 로그인해도 데이터가 복구되지 않습니다.",
            "まだ購読がありません。" to "아직 구독이 없습니다.",
            "アカウントを削除すると購読・タグ・記事の状態がすべて削除され、再ログインしても復元されません。" to "계정을 삭제하면 구독, 태그, 기사 상태가 모두 삭제되며 다시 로그인해도 복구되지 않습니다.",
            "タグを上へ" to "태그 위로 이동",
            "タグを下へ" to "태그 아래로 이동",
            "パスワードリセットメールを送信しました" to "비밀번호 재설정 이메일을 보냈습니다",
            "フィード" to "피드",
            "フィードURL" to "피드 URL",
            "フィードURLを表示" to "피드 URL 보기",
            "フィードを確認中…" to "피드를 확인하는 중…",
            "フィードメニュー" to "피드 메뉴",
            "リーディングリストに保存した記事はありません。" to "읽기 목록에 저장된 기사가 없습니다.",
            "並び順" to "정렬 순서",
            "公開日時が新しい順" to "게시일 최신순",
            "再試行中…" to "다시 시도하는 중…",
            "処理ステータス" to "처리 상태",
            "分" to "분",
            "初回取得失敗" to "첫 가져오기 실패",
            "削除" to "삭제",
            "削除処理は自動的に再試行されます。時間をおいてもこの状態が続く場合はお問い合わせください。" to "삭제는 자동으로 다시 시도됩니다. 계속되면 문의하세요.",
            "取得に時間がかかっています。あとで再度更新してください。" to "가져오는 데 시간이 걸립니다. 나중에 다시 시도하세요.",
            "取得中" to "가져오는 중",
            "取得日時が新しい順" to "가져온 시간 최신순",
            "名前を変更" to "이름 변경",
            "新しいパスワード" to "새 비밀번호",
            "新しいパスワードを入力してください" to "새 비밀번호를 입력하세요",
            "新規タグ（カンマ区切り）" to "새 태그(쉼표로 구분)",
            "既読で並び替えない" to "읽음 상태로 정렬하지 않음",
            "既読の扱い" to "읽음 처리",
            "既読は上" to "읽은 항목 먼저",
            "既読は下" to "읽은 항목 나중",
            "既読状態" to "읽음 상태",
            "日" to "일",
            "日本語" to "일본어",
            "時間" to "시간",
            "最終取得" to "마지막 가져오기",
            "最近取得済みのため、今回の取得対象はありませんでした。" to "최근에 가져와 이번에는 대상이 없습니다.",
            "条件に一致する購読がありません。" to "조건에 맞는 구독이 없습니다.",
            "翻訳の準備" to "번역 준비",
            "表示できる記事がありません。" to "표시할 기사가 없습니다.",
            "表示設定" to "표시 설정",
            "言語を確認" to "언어 확인",
            "記事の取得が完了しています。" to "기사를 준비했습니다.",
            "記事を取得しています…" to "기사를 가져오는 중…",
            "記事一覧へ" to "기사 목록으로",
            "読み上げ中" to "읽어주는 중",
            "購読の操作" to "구독 작업",
            "購読の追加は完了しました。記事を取得しています。" to "구독이 추가되었습니다. 기사를 가져오는 중입니다.",
            "追加 %d / スキップ %d / 失敗 %d" to "추가 %d / 건너뜀 %d / 실패 %d",
            "追加完了" to "추가됨",
            "閲覧履歴は既読記事として扱われます。記事一覧の絞り込みから既読記事を確認できます。" to "읽기 기록은 읽은 기사로 처리됩니다. 기사 목록 필터에서 확인할 수 있습니다.",
        ),
        "es" to mapOf(
            "J / ↓  次の記事" to "J / ↓  Siguiente artículo",
            "K / ↑  前の記事" to "K / ↑  Artículo anterior",
            "RSS/Atom URL または サイトURL" to "URL de RSS/Atom o del sitio",
            "URLをリーディングリストに保存します。" to "Guarda la URL en tu lista de lectura.",
            "V  元記事を開く" to "V  Abrir original",
            "この画面を閉じても削除処理は継続されます。再ログインでデータが復活することはありません。" to "La eliminación continúa aunque cierres esta pantalla. Volver a iniciar sesión no restaurará los datos.",
            "まだ購読がありません。" to "Aún no tienes suscripciones.",
            "アカウントを削除すると購読・タグ・記事の状態がすべて削除され、再ログインしても復元されません。" to "Eliminar tu cuenta borra suscripciones, etiquetas y estados de artículos. Volver a iniciar sesión no los restaurará.",
            "タグを上へ" to "Subir etiqueta",
            "タグを下へ" to "Bajar etiqueta",
            "パスワードリセットメールを送信しました" to "Se envió el correo para restablecer la contraseña",
            "フィード" to "Feeds",
            "フィードURL" to "URL del feed",
            "フィードURLを表示" to "Mostrar URL del feed",
            "フィードを確認中…" to "Comprobando el feed…",
            "フィードメニュー" to "Menú del feed",
            "リーディングリストに保存した記事はありません。" to "No hay artículos guardados en la lista de lectura.",
            "並び順" to "Orden",
            "公開日時が新しい順" to "Publicados más recientemente",
            "再試行中…" to "Reintentando…",
            "処理ステータス" to "Estado",
            "分" to "min",
            "初回取得失敗" to "Error en la obtención inicial",
            "削除" to "Eliminar",
            "削除処理は自動的に再試行されます。時間をおいてもこの状態が続く場合はお問い合わせください。" to "La eliminación se reintentará automáticamente. Contacta con soporte si continúa así.",
            "取得に時間がかかっています。あとで再度更新してください。" to "La obtención está tardando. Inténtalo más tarde.",
            "取得中" to "Obteniendo",
            "取得日時が新しい順" to "Obtenidos más recientemente",
            "名前を変更" to "Cambiar nombre",
            "新しいパスワード" to "Nueva contraseña",
            "新しいパスワードを入力してください" to "Introduce una nueva contraseña",
            "新規タグ（カンマ区切り）" to "Nuevas etiquetas (separadas por comas)",
            "既読で並び替えない" to "No ordenar por leído",
            "既読の扱い" to "Gestión de leídos",
            "既読は上" to "Leídos primero",
            "既読は下" to "Leídos al final",
            "既読状態" to "Estado de lectura",
            "日" to "d",
            "日本語" to "Japonés",
            "時間" to "h",
            "最終取得" to "Última obtención",
            "最近取得済みのため、今回の取得対象はありませんでした。" to "Todo se obtuvo recientemente; no hay tareas nuevas.",
            "条件に一致する購読がありません。" to "Ninguna suscripción coincide con los filtros.",
            "翻訳の準備" to "Preparar traducción",
            "表示できる記事がありません。" to "No hay artículos para mostrar.",
            "表示設定" to "Configuración de vista",
            "言語を確認" to "Ver idiomas",
            "記事の取得が完了しています。" to "Los artículos están listos.",
            "記事を取得しています…" to "Obteniendo artículos…",
            "記事一覧へ" to "Ver artículos",
            "読み上げ中" to "Leyendo en voz alta",
            "購読の操作" to "Acciones de suscripción",
            "購読の追加は完了しました。記事を取得しています。" to "Suscripción añadida. Obteniendo artículos.",
            "追加 %d / スキップ %d / 失敗 %d" to "Añadidas %d / Omitidas %d / Fallidas %d",
            "追加完了" to "Añadido",
            "閲覧履歴は既読記事として扱われます。記事一覧の絞り込みから既読記事を確認できます。" to "El historial de lectura se trata como artículos leídos. Usa los filtros para verlos.",
        ),
    )

    private val remainingTranslations = mapOf(
        "en" to mapOf(
            "Esc  戻る" to "Esc  Back",
            "この購読を解除しますか？" to "Unsubscribe from this subscription?",
            "たった今" to "just now",
            "タイトルの翻訳はこの端末の中で行います。はじめに、翻訳したい言語をダウンロードしてください。ダウンロードは Wi-Fi 接続時をおすすめします。" to "Titles are translated on this device. Download the languages you want first. Wi-Fi is recommended.",
            "タイトルを翻訳（オフ）" to "Translate titles (off)",
            "タイトルを翻訳（オン）" to "Translate titles (on)",
            "タグ「%s」を削除しますか？" to "Delete tag \"%s\"?",
            "ダウンロード中…" to "Downloading…",
            "パスワードをリセット" to "Reset password",
            "ブックマークした記事は残ります。" to "Bookmarked articles will be kept.",
            "メールに記載されたリセットコードを入力してください。" to "Enter the reset code from the email.",
            "メールアドレスとパスワードでアカウントを作成します。" to "Create an account with your email address and password.",
            "メールアドレスとパスワードでサインインします。" to "Sign in with your email address and password.",
            "リセットコード" to "Reset code",
            "リセットコードを入力" to "Enter the reset code",
            "リセットメールを送信" to "Send reset email",
            "リセットメールを送信できませんでした" to "Could not send the reset email",
            "リセットリンクと8文字以上のパスワードを確認してください" to "Check the reset link and password (at least 8 characters).",
            "リセットリンクを開いてください" to "Open the reset link",
            "リーディングリストから削除できませんでした。" to "Could not remove from the reading list.",
            "リーディングリストに追加できませんでした。" to "Could not add to the reading list.",
            "リーディングリストを開始できませんでした。" to "Could not start the reading list.",
            "分前" to "min ago",
            "展開" to "Expand",
            "折りたたむ" to "Collapse",
            "一時停止中" to "Paused",
            "再生" to "Play",
            "再生中 %d/%d" to "Playing %d/%d",
            "再読み込み" to "Reload",
            "新しいパスワードを入力してください。" to "Enter a new password.",
            "新しいパスワードを設定" to "Set a new password",
            "新しいパスワード（確認）" to "Confirm new password",
            "日前" to "days ago",
            "時間前" to "hr ago",
            "最終取得 %s" to "Last fetched %s",
            "登録済みのメールアドレスにリセット用のリンクを送信します。" to "Send a reset link to your registered email address.",
            "色 (#hex)" to "Color (#hex)",
            "解除" to "Clear",
            "記事の読み上げ再生中に表示されます" to "Shown while an article is being read aloud",
            "購読は削除されません。" to "Subscriptions will not be deleted.",
        ),
        "zh" to mapOf(
            "Check your internet connection and try again." to "请检查网络连接后重试。",
            "Retry" to "重试",
            "Unable to connect" to "无法连接",
            "Esc  戻る" to "Esc  返回",
            "S  リーディングリストに追加" to "S  加入阅读列表",
            "Space  読み上げ開始／停止" to "Space  开始/停止朗读",
            "V  元記事を開く" to "V  打开原文",
            "たった今" to "刚刚",
            "タイトルの翻訳はこの端末の中で行います。はじめに、翻訳したい言語をダウンロードしてください。ダウンロードは Wi-Fi 接続時をおすすめします。" to "标题会在此设备上翻译。请先下载需要的语言，建议使用 Wi-Fi。",
            "メールに記載されたリセットコードを入力してください。" to "请输入邮件中的重置代码。",
            "メールアドレスと8文字以上のパスワードが必要です" to "需要邮箱地址和至少 8 个字符的密码",
            "メールアドレスとパスワードでアカウントを作成します。" to "使用邮箱地址和密码创建账户。",
            "メールアドレスとパスワードでサインインします。" to "使用邮箱地址和密码登录。",
            "リセットコード" to "重置代码",
            "リセットコードを入力" to "输入重置代码",
            "リセットメールを送信" to "发送重置邮件",
            "リセットメールを送信できませんでした" to "无法发送重置邮件",
            "リセットリンクと8文字以上のパスワードを確認してください" to "请检查重置链接和至少 8 个字符的密码",
            "リセットリンクを開いてください" to "请打开重置链接",
            "リーディングリストから削除できませんでした。" to "无法从阅读列表中删除。",
            "リーディングリストに追加できませんでした。" to "无法加入阅读列表。",
            "リーディングリストを開始できませんでした。" to "无法开始阅读列表。",
            "分前" to "分钟前",
            "展開" to "展开",
            "折りたたむ" to "收起",
            "新しいパスワードを入力してください。" to "请输入新密码。",
            "新しいパスワードを設定" to "设置新密码",
            "新しいパスワード（確認）" to "确认新密码",
            "日前" to "天前",
            "時間前" to "小时前",
            "登録済みのメールアドレスにリセット用のリンクを送信します。" to "我们会向已注册的邮箱发送重置链接。",
            "記事" to "文章",
            "記事の読み上げ再生中に表示されます" to "朗读文章时显示",
        ),
        "ko" to mapOf(
            "Check your internet connection and try again." to "인터넷 연결을 확인한 후 다시 시도하세요.",
            "Retry" to "다시 시도",
            "Unable to connect" to "연결할 수 없습니다",
            "Esc  戻る" to "Esc  뒤로",
            "S  リーディングリストに追加" to "S  읽기 목록에 추가",
            "Space  読み上げ開始／停止" to "Space  낭독 시작/중지",
            "V  元記事を開く" to "V  원문 열기",
            "たった今" to "방금",
            "タイトルの翻訳はこの端末の中で行います。はじめに、翻訳したい言語をダウンロードしてください。ダウンロードは Wi-Fi 接続時をおすすめします。" to "제목은 이 기기에서 번역됩니다. 먼저 원하는 언어를 다운로드하세요. Wi-Fi 사용을 권장합니다.",
            "メールに記載されたリセットコードを入力してください。" to "이메일에 있는 재설정 코드를 입력하세요.",
            "メールアドレスと8文字以上のパスワードが必要です" to "이메일 주소와 8자 이상의 비밀번호가 필요합니다",
            "メールアドレスとパスワードでアカウントを作成します。" to "이메일 주소와 비밀번호로 계정을 만듭니다.",
            "メールアドレスとパスワードでサインインします。" to "이메일 주소와 비밀번호로 로그인합니다.",
            "リセットコード" to "재설정 코드",
            "リセットコードを入力" to "재설정 코드 입력",
            "リセットメールを送信" to "재설정 이메일 보내기",
            "リセットメールを送信できませんでした" to "재설정 이메일을 보내지 못했습니다",
            "リセットリンクと8文字以上のパスワードを確認してください" to "재설정 링크와 8자 이상의 비밀번호를 확인하세요",
            "リセットリンクを開いてください" to "재설정 링크를 여세요",
            "リーディングリストから削除できませんでした。" to "읽기 목록에서 삭제하지 못했습니다.",
            "リーディングリストに追加できませんでした。" to "읽기 목록에 추가하지 못했습니다.",
            "リーディングリストを開始できませんでした。" to "읽기 목록을 시작하지 못했습니다.",
            "分前" to "분 전",
            "展開" to "펼치기",
            "折りたたむ" to "접기",
            "新しいパスワードを入力してください。" to "새 비밀번호를 입력하세요.",
            "新しいパスワードを設定" to "새 비밀번호 설정",
            "新しいパスワード（確認）" to "새 비밀번호 확인",
            "日前" to "일 전",
            "時間前" to "시간 전",
            "登録済みのメールアドレスにリセット用のリンクを送信します。" to "등록된 이메일 주소로 재설정 링크를 보냅니다.",
            "記事" to "기사",
            "記事の読み上げ再生中に表示されます" to "기사 낭독 중 표시됩니다",
        ),
        "es" to mapOf(
            "Check your internet connection and try again." to "Comprueba tu conexión a Internet e inténtalo de nuevo.",
            "Retry" to "Reintentar",
            "Unable to connect" to "No se puede conectar",
            "Esc  戻る" to "Esc  Atrás",
            "S  リーディングリストに追加" to "S  Añadir a la lista de lectura",
            "Space  読み上げ開始／停止" to "Space  Iniciar/detener lectura",
            "V  元記事を開く" to "V  Abrir original",
            "たった今" to "ahora mismo",
            "タイトルの翻訳はこの端末の中で行います。はじめに、翻訳したい言語をダウンロードしてください。ダウンロードは Wi-Fi 接続時をおすすめします。" to "Los títulos se traducen en este dispositivo. Descarga primero los idiomas que quieras; se recomienda usar Wi-Fi.",
            "メールに記載されたリセットコードを入力してください。" to "Introduce el código de restablecimiento del correo.",
            "メールアドレスと8文字以上のパスワードが必要です" to "Se necesita un correo electrónico y una contraseña de al menos 8 caracteres",
            "メールアドレスとパスワードでアカウントを作成します。" to "Crea una cuenta con tu correo electrónico y contraseña.",
            "メールアドレスとパスワードでサインインします。" to "Inicia sesión con tu correo electrónico y contraseña.",
            "リセットコード" to "Código de restablecimiento",
            "リセットコードを入力" to "Introduce el código de restablecimiento",
            "リセットメールを送信" to "Enviar correo de restablecimiento",
            "リセットメールを送信できませんでした" to "No se pudo enviar el correo de restablecimiento",
            "リセットリンクと8文字以上のパスワードを確認してください" to "Comprueba el enlace y la contraseña de al menos 8 caracteres",
            "リセットリンクを開いてください" to "Abre el enlace de restablecimiento",
            "リーディングリストから削除できませんでした。" to "No se pudo quitar de la lista de lectura.",
            "リーディングリストに追加できませんでした。" to "No se pudo añadir a la lista de lectura.",
            "リーディングリストを開始できませんでした。" to "No se pudo iniciar la lista de lectura.",
            "分前" to "hace min",
            "展開" to "Expandir",
            "折りたたむ" to "Contraer",
            "新しいパスワードを入力してください。" to "Introduce una nueva contraseña.",
            "新しいパスワードを設定" to "Establecer nueva contraseña",
            "新しいパスワード（確認）" to "Confirmar nueva contraseña",
            "日前" to "hace días",
            "時間前" to "hace horas",
            "登録済みのメールアドレスにリセット用のリンクを送信します。" to "Enviaremos un enlace de restablecimiento a tu correo registrado.",
            "記事" to "Artículos",
            "記事の読み上げ再生中に表示されます" to "Se muestra mientras se lee un artículo en voz alta",
        ),
    )

    private val commonEnglish = mapOf(
        "パスワードをリセット" to "Reset password", "リセットコードを入力" to "Enter the reset code", "新しいパスワードを設定" to "Set a new password", "メールアドレスとパスワードでサインインします。" to "Sign in with your email address and password.", "メールアドレスとパスワードでアカウントを作成します。" to "Create an account with your email address and password.", "登録済みのメールアドレスにリセット用のリンクを送信します。" to "Send a reset link to your registered email address.", "メールに記載されたリセットコードを入力してください。" to "Enter the reset code from the email.", "新しいパスワードを入力してください。" to "Enter a new password.", "リセットメールを送信できませんでした" to "Could not send the reset email", "リセットリンクを開いてください" to "Open the reset link", "パスワードを変更できませんでした" to "Could not change the password", "ログイン状態を確認しています…" to "Checking sign-in status…", "新しいパスワード" to "New password", "新しいパスワード（確認）" to "Confirm new password", "たった今" to "just now", "分前" to "min ago", "時間前" to "hr ago", "日前" to "days ago", "今" to "now", "分" to "m", "時間" to "h", "日" to "d", "Esc  戻る" to "Esc  Back", "更新異常" to "Update error", "再読み込み" to "Reload", "操作" to "Actions", "購読" to "Subscription", "すべて取得" to "Fetch all", "約%d秒ごとに自動更新" to "Auto-refreshes about every %d seconds", "購読一覧（%d件）" to "Subscriptions (%d)", "購読 %d件・記事 %d件" to "%d subscriptions · %d articles", "最終取得 %s" to "Last fetched %s", "並び替え: %s" to "Sort: %s", "購読詳細" to "Subscription details", "購読一覧へ戻る" to "Back to subscriptions", "購読名を変更" to "Rename subscription", "空欄でフィード名に戻す" to "Leave blank to use the feed name", "コピー" to "Copy", "変更" to "Save", "フィード追加" to "Add feed", "更新停止中" to "Updates paused", "しばらく更新なし" to "No recent updates", "タイトルを翻訳（オン）" to "Translate titles (on)", "タイトルを翻訳（オフ）" to "Translate titles (off)", "原文タイトルに戻す" to "Show original titles", "タイトルを翻訳" to "Translate titles", "翻訳の準備" to "Prepare translation", "タイトルの翻訳はこの端末の中で行います。はじめに、翻訳したい言語をダウンロードしてください。ダウンロードは Wi-Fi 接続時をおすすめします。" to "Titles are translated on this device. Download the languages you want to translate first. Wi-Fi is recommended.", "確認しています…" to "Checking…", "購読しているフィードに、翻訳が必要な言語はありません。" to "None of your subscribed feeds need translation.", "準備済み" to "Ready", "ダウンロード中…" to "Downloading…", "ダウンロード" to "Download", "この端末では非対応" to "Not supported on this device", "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "Articles in languages not listed here remain in the original language.", "リスト" to "List", "読み上げ" to "Reading aloud", "再生" to "Play", "一時停止" to "Pause", "一時停止中" to "Paused", "再生中 %d/%d" to "Playing %d/%d", "記事の読み上げ再生中に表示されます" to "Shown while an article is being read aloud", "状態を確認しています…" to "Checking status…", "削除完了" to "Deleted", "アカウントの削除が完了しました。ご利用ありがとうございました。" to "Your account has been deleted. Thank you for using Filo.", "再ログインしてもデータは復元されません。" to "Your data cannot be restored by signing in again.", "削除処理に失敗しました" to "Account deletion failed", "削除処理は自動的に再試行されます。時間をおいてもこの状態が続く場合はお問い合わせください。" to "Deletion will be retried automatically. Contact support if this continues.", "進行中の削除処理はありません。" to "There is no deletion in progress.", "設定へ戻る" to "Back to settings", "削除処理中…" to "Deleting…", "この画面を閉じても削除処理は継続されます。再ログインでデータが復活することはありません。" to "Deletion continues even if you close this screen. Signing in again will not restore your data.", "購読は作成されましたが、%s" to "The subscription was created, but %s", "購読が見つかりません" to "Subscription not found", "この購読を解除しますか？" to "Unsubscribe from this subscription?", "ブックマークした記事は残ります。" to "Bookmarked articles will be kept.", "購読記事を読み込んでいます…" to "Loading subscription articles…", "次の記事を読み込んでいます…" to "Loading more articles…", "取得に時間がかかっています。あとで再度更新してください。" to "Fetching is taking longer than expected. Try again later.", "この記事を開く" to "Open this article", "表示できる記事がありません。" to "No articles to display.", "フィードに接続できませんでした。" to "Could not connect to the feed.", "フィードを見つけられませんでした。" to "Could not find the feed.", "コピー" to "Copy", "フィード追加" to "Add feed", "変更" to "Save", "削除" to "Delete", "新しいパスワード" to "New password", "新しいパスワード（確認）" to "Confirm new password", "すべて取得" to "Fetch all", "フィードの取得を開始しました。" to "Feed fetch started.", "%d件のフィードの取得を開始しました。" to "Started fetching %d feeds.", "ここに無い言語の記事は、翻訳せず原文のまま表示します。" to "Articles in languages not listed here remain in the original language.", "記事の読み上げ再生中に表示されます" to "Shown while an article is being read aloud", "取得対象のフィードがありません。" to "There are no feeds to fetch.", "この操作は取り消せません。" to "This cannot be undone.", "アカウントを削除すると購読・タグ・記事の状態がすべて削除され、再ログインしても復元されません。" to "Deleting your account removes all subscriptions, tags, and article state. It cannot be restored by signing in again.", "閲覧履歴は既読記事として扱われます。記事一覧の絞り込みから既読記事を確認できます。" to "Browsing history is treated as read articles. You can view read articles using the article list filters.",
        "タグ「%s」を削除しますか？" to "Delete tag \"%s\"?", "タグがありません。上の入力欄から作成できます。" to "No tags. Create one using the field above.", "タグ名" to "Tag name", "新しいタグ名" to "New tag name", "フィード" to "Feeds", "色 (#hex)" to "Color (#hex)", "解除" to "Clear", "保存" to "Save", "編集" to "Edit", "購読は削除されません。" to "Subscriptions will not be deleted.", "リセットコード" to "Reset code", "J / ↓  次の記事" to "J / ↓  Next article", "K / ↑  前の記事" to "K / ↑  Previous article", "Enter / O  記事を開く" to "Enter / O  Open article", "V  元記事を開く" to "V  Open original", "M  既読／未読" to "M  Mark read / unread", "S  リーディングリスト" to "S  Reading list", "B  ブックマーク" to "B  Bookmark", "R  更新" to "R  Refresh", "Shift+A  すべて既読" to "Shift+A  Mark all as read", "?  この一覧" to "?  This list", "この操作を行う権限がありません。" to "You do not have permission to perform this action.", "サーバーエラーが発生しました。時間をおいて再試行してください。" to "A server error occurred. Please try again later.", "この購読は再試行できる状態ではありません。" to "This subscription cannot be retried in its current state.", "インポートジョブが見つかりません。" to "Import job not found.", "原文の言語を判定できませんでした。" to "Could not detect the original language.",
    )

    fun languageName(code: String): String = get(
        when (code) {
            "ja" -> "日本語"
            "en" -> "English"
            "zh" -> "简体中文"
            "ko" -> "한국어"
            "es" -> "Español"
            else -> code
        },
    )

    fun get(source: String): String {
        val language = LanguagePreference.load(FiloApplication.context)
        return translations[language]?.get(source)
            ?: supplementalTranslations[language]?.get(source)
            ?: resourceTranslations[language]?.get(source)
            ?: remainingTranslations[language]?.get(source)
            ?: commonEnglish[source]
            ?: translations["en"]?.get(source)
            ?: source
    }

    fun format(source: String, vararg args: Any): String = runCatching {
        String.format(Locale.forLanguageTag(LanguagePreference.load(FiloApplication.context)), get(source), *args)
    }.getOrElse { get(source) }
}

@Composable
fun tr(source: String): String = AppStrings.get(source)

@Composable
fun trf(source: String, vararg args: Any): String = AppStrings.format(source, *args)
